---

- name: store facts from all hosts in a variable
  set_fact: host_fact={{hostvars[item]["res"]}}
  with_items: "{{groups.alpha}}"
  register: host_facts

- name: parse variable into a list of dictionaries
  set_fact: host_facts="{{ host_facts.results | map(attribute="ansible_facts.host_fact") | list }}"

- name: write the list to a csv
  spit_results: name=spit file_path={{report_path}} vals={{host_facts}}
